# Generated by Django 3.2.3 on 2021-07-01 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmsId', models.IntegerField()),
                ('lmsPwd', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('stamp', models.IntegerField()),
                ('calendar_type', models.IntegerField()),
                ('font', models.IntegerField()),
                ('type', models.IntegerField()),
                ('language', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
